---
title: Bookshelf
subtitle: Recommended Books
comments: false
---

---

  <div align="center">*Felix, qui potuit rerum cognoscere causas.*  
  Virgil, Georgica, lib. 2[^1]
  </div>

---

## <i class="fas fa-microscope"></i> Microbes  

- Ingraham. *March of the Microbes: Sighting the Unseen.*  

- Kirchman. *Processes in Microbial Ecology.*

- Kolter and Chimileski. *Life at the Edge of Sight: A Photographic Exploration of the Microbial World.*  

- O'Malley. *Philosophy of Microbiology.*  

---

## <i class="fas fa-leaf"></i> Plants  

- Karban. *Plant Sensing & Communication.*  

- Trewavas. *Plant Behavior & Intelligence.*  

---

## <i class="fas fa-seedling"></i> Agriculture  

- Brown. *Feed or Feedback: Agriculture, Population Dynamics and the State of the Planet.* 

- Denison. *Darwinian Agriculture: How Understanding Evolution Can Improve Agriculture.*  

- Smil. *Enriching the Earth: Fritz Haber, Carl Bosch, and the Transformation of World Food Production.*

---

## <i class="fas fa-book-open"></i> General

### <i class="fas fa-dna"></i> Biology

- Kozo-Polyansky. *Symbiogenesis: A New Principle of Evolution.*

- Levins and Lewontin. *The Dialectical Biologist.*

- Sapp. *Evolution by Association: A History of Symbiosis.* 

### <i class="far fa-snowflake"></i> Complex Systems

- Bechtel and Richardson. *Discovering Complexity: Decomposition and Localization as Strategies in Scientific Research.*

- Wimsatt. *Re-Engineering Philosophy for Limited Beings: Piecewise Approximations to Reality.*

---

[^1]: *Fortunate is the one who can know the causes of things.* Virgil, Georgics, book 2

