---
title: Research
subtitle: Soil - Plant - Microbiota Interactions
comments: false
---

---

<div align="center">*Sit down before fact like a little child, and be prepared to give up every preconceived notion, follow humbly wherever and to whatever abyss Nature leads or you shall learn nothing.*  
Thomas Henry Huxley
</div>

---

## Research Goals and Interests
My long-term goal is to develop a microbiome-informed agronomy taking into account the evolutionary and ecological complexity of plant-microbiota interactions in agricultural soils.

My interests include:  

- The rhizosphere effect and plant immune interactions with the microbiota in community assembly.  
- The symbiosis continuum of the root and soil microbiome: pathogens, commensals, and mutualists.  
- The microbial ecology of biogeochemical cycling (e.g., nitrogen and carbon).  

---

## Publications  
Edwards, J., Santos-Medellín, C., Nguyen, B., Kilmer,  J., Liechty, Z., **Veliz, E.**, Ni, J., Phillips, G.,  Sundaresan, V. (2019). *Soil domestication by rice cultivation results in plant-soil feedback through shifts in soil microbiota.* Genome Biology 2019 20:1, 20(1), 1–14. [doi:10.11 86/s13059-019-1825-x](https://doi.org/10.1186/s13059-019-1825-x) (<i class="ai ai-open-access"></i>open access)    

**Veliz, Esteban A.**, Martínez-Hidalgo, Pilar, Hirsch, Ann M., *Chitinase-producing bacteria and their role in biocontrol.* (Review) AIMS Microbiology, 2017, 3(3): 689-705. [doi: 10.3934/microbiol.2017.3.689](https://doi.org/10.3934/microbiol.2017.3.689) (<i class="ai ai-open-access"></i>open access)
